import {League, Club} from "./entities";

export const LEAGUES = {
    PREMIER_LEAGUE: new League(79, "England", "PREMIER LEAGUE"),
    LALIGA_EA_SPORTS: new League(77, "Spain", "LALIGA EASPORTS"),
    BUNDESLIGA: new League(76, "Germany", "BUNDESLIGA"),
    SERIE_A: new League(76, "Italy", "SERIE A"),
    LIGUE_1: new League(75, "France", "LIGUE 1"),
    EFL_CHAMPIONSHIP: new League(70, "England", "EFL CHAMPIONSHIP"),
    SUPER_LIG: new League(70, "Turkey", "SUPERLIG"),
    LIGA_PORTUGAL: new League(70, "Portugal", "LIGA PORTUGAL"),
    PRO_LEAGUE_BELGIUM: new League(69, "Belgium", "PROLEAGUE BELGIUM"),
    EREDIVISIE: new League(69, "Netherlands", "EREDIVISIE"),
    SERIE_B: new League(68, "Italy", "SERIEB"),
    MLS: new League(68, "United States", "MLS"),
    BUNDESLIGA_2: new League(68, "Germany", "BUNDESLIGA 2"),
    LALIGA_HYPERMOTION: new League(68, "Spain", "LALIGA HYPERMOTION"),
    ROSHN_SAUDI_LEAGUE: new League(68, "Saudi Arabia", "ROSHN SAUDI LEAGUE"),
    LIGA_PROFESIONAL_ARGENTINA: new League(69, "Argentina", "LIGA PROFESIONAL ARGENTINA"),
    SUPERLIGA_DENMARK: new League(67, "Denmark", "SUPERLIGA DENMARK"),
    SCOTTISH_PREMIERSHIP: new League(67, "Scotland", "SCOTTISH PREMIERSHIP"),
    CREDIT_SUISSE_SUPER_LEAGUE: new League(67, "Switzerland", "CREDIT SUISSE SUPERLEAGUE"),
    LIGUE_2: new League(66, "France", "LIGUE 2"),
    EKSTRAKLASA: new League(66, "Poland", "EKSTRAKLASA"),
    AUSTRIAN_BUNDESLIGA: new League(66, "Austria", "AUSTRIANBUNDESLIGA"),
    ELITESERIEN: new League(65, "Norway", "ELITESERIEN"),
    ALLSVENSKAN: new League(65, "Sweden", "ALLSVENSKAN"),
    EFL_LEAGUE_ONE: new League(65, "England", "EFL LEAGUE ONE"),
    K_LEAGUE_1: new League(65, "Korea Republic", "K LEAGU 1"),
    SUPERLIGA_ROMANIA: new League(65, "Romania", "SUPERLIGA ROMANIA"),
    GERMAN_3_LIGA: new League(64, "Germany", "GERMA 3 LIGA"),
    A_LEAGUE: new League(63, "Australia", "A LEAGUE"),
    EFL_LEAGUE_TWO: new League(62, "England", "EFL LEAGUE TWO"),
    CHINESE_SUPER_LEAGUE: new League(62, "China PR", "CHINESE SUPERLEAGUE"),
    SSE_AIRTRICITY_PREMIER: new League(60, "Republic of Ireland", "SSE AIRTRICITY PREMIER"),
};

export const PREMIER_LEAGUE_CLUBS = {
    SPURS: new Club(LEAGUES.PREMIER_LEAGUE, 80, "Spurs"),
    CHELSEA: new Club(LEAGUES.PREMIER_LEAGUE, 81, "Chelsea"),
    // BURNLEY: new Club(LEAGUES.PREMIER_LEAGUE, 75),
    EVERTON: new Club(LEAGUES.PREMIER_LEAGUE, 78, "Everton"),
    MAN_UTD: new Club(LEAGUES.PREMIER_LEAGUE, 80, "Man Utd"),
    LIVERPOOL: new Club(LEAGUES.PREMIER_LEAGUE, 84, "Liverpool"),
    MANCHESTER_CITY: new Club(LEAGUES.PREMIER_LEAGUE, 84, "Manchester City"),
    LEEDS_UNITED: new Club(LEAGUES.PREMIER_LEAGUE, 76, "Leeds United"),
    SUNDERLAND: new Club(LEAGUES.PREMIER_LEAGUE, 77, "Sunderland"),
    FULHAM: new Club(LEAGUES.PREMIER_LEAGUE, 78, "Fulham"),
    BRENTFORD: new Club(LEAGUES.PREMIER_LEAGUE, 78, "Brentford"),
    AFC_BOURNEMOUTH: new Club(LEAGUES.PREMIER_LEAGUE, 78, "AFC Bournemouth"),
    ARSENAL: new Club(LEAGUES.PREMIER_LEAGUE, 84, "Arsenal"),
    NOTTM_FOREST: new Club(LEAGUES.PREMIER_LEAGUE, 79, "Nottm Forest"),
    // WEST_HAM: new Club(LEAGUES.PREMIER_LEAGUE, 77),
    NEWCASTLE_UTD: new Club(LEAGUES.PREMIER_LEAGUE, 81, "Newcastle Utd"),
    ASTON_VILLA: new Club(LEAGUES.PREMIER_LEAGUE, 81, "Aston Villa"),
    // WOLVES: new Club(LEAGUES.PREMIER_LEAGUE, 75),
    BRIGHTON: new Club(LEAGUES.PREMIER_LEAGUE, 78, "Brighton"),
    CRYSTAL_PALACE: new Club(LEAGUES.PREMIER_LEAGUE, 79, "Crystal Palace")
};

export const LIGUE_1_CLUBS = {
    STADE_BRESTOIS_29: new Club(LEAGUES.LIGUE_1, 74, "Stade Brestois 29"),
    LOSC_LILLE: new Club(LEAGUES.LIGUE_1, 77, "LOSC Lille"),
    RC_LENS: new Club(LEAGUES.LIGUE_1, 77, "RC Lens"),
    STRASBOURG: new Club(LEAGUES.LIGUE_1, 75, "Strasbourg"),
    OGC_NICE: new Club(LEAGUES.LIGUE_1, 75, "OGC Nice"),
    TOULOUSE_FC: new Club(LEAGUES.LIGUE_1, 73, "Toulouse FC"),
    STADE_RENNAIS_FC: new Club(LEAGUES.LIGUE_1, 76, "Stade Rennais FC"),
    HAVRE_AC: new Club(LEAGUES.LIGUE_1, 72, "Havre AC"),
    AS_MONACO: new Club(LEAGUES.LIGUE_1, 78, "AS Monaco"),
    OM: new Club(LEAGUES.LIGUE_1, 79, "OM"),
    PARIS_FC: new Club(LEAGUES.LIGUE_1, 75, "Paris FC"),
    // FC_NANTES: new Club(LEAGUES.LIGUE_1, 72),
    FC_LORIENT: new Club(LEAGUES.LIGUE_1, 73, "FC Lorient"),
    PARIS_SG: new Club(LEAGUES.LIGUE_1, 85, "Paris SG"),
    AJ_AUXERRE: new Club(LEAGUES.LIGUE_1, 72, "AJ Auxerre"),
    ANGERS_SCO: new Club(LEAGUES.LIGUE_1, 72, "Angers SCO"),
    OL: new Club(LEAGUES.LIGUE_1, 77, "OL"),
    // FC_METZ: new Club(LEAGUES.LIGUE_1, 71)
};

export const BUNDESLIGA_CLUBS = {
    FC_AUGSBURG: new Club(LEAGUES.BUNDESLIGA, 74, "FC Augsburg"),
    LEVERKUSEN: new Club(LEAGUES.BUNDESLIGA, 79, "Leverkusen"),
    BORUSSIA_DORTMUND: new Club(LEAGUES.BUNDESLIGA, 81, "Borussia Dortmund"),
    RB_LEIPZIG: new Club(LEAGUES.BUNDESLIGA, 79, "RB Leipzig"),
    FC_KOLN: new Club(LEAGUES.BUNDESLIGA, 74, "FC Köln"),
    VFB_STUTTGART: new Club(LEAGUES.BUNDESLIGA, 77, "VfB Stuttgart"),
    // FC_ST_PAULI: new Club(LEAGUES.BUNDESLIGA, 72),
    SV_WERDER_BREMEN: new Club(LEAGUES.BUNDESLIGA, 75, "SV Werder Bremen"),
    MGLADBACH: new Club(LEAGUES.BUNDESLIGA, 75, "M'gladbach"),
    FC_BAYERN_MUNCHEN: new Club(LEAGUES.BUNDESLIGA, 84, "FC Bayern München"),
    TSG_HOFFENHEIM: new Club(LEAGUES.BUNDESLIGA, 77, "TSG Hoffenheim"),
    SC_FREIBURG: new Club(LEAGUES.BUNDESLIGA, 75, "SC Freiburg"),
    UNION_BERLIN: new Club(LEAGUES.BUNDESLIGA, 74, "Union Berlin"),
    FRANKFURT: new Club(LEAGUES.BUNDESLIGA, 77, "Frankfurt"),
    // VFL_WOLFSBURG: new Club(LEAGUES.BUNDESLIGA, 76),
    MAINZ_05: new Club(LEAGUES.BUNDESLIGA, 75, "Mainz 05"),
    // HEIDENHEIM: new Club(LEAGUES.BUNDESLIGA, 72),
    HAMBURGER_SV: new Club(LEAGUES.BUNDESLIGA, 74, "Hamburger SV")
};

export const SERIE_A_CLUBS = {
    FIORENTINA: new Club(LEAGUES.SERIE_A, 76, "Fiorentina"),
    TORINO: new Club(LEAGUES.SERIE_A, 75, "Torino"),
    SSC_NAPOLI: new Club(LEAGUES.SERIE_A, 81, "SSC Napoli"),
    CAGLIARI: new Club(LEAGUES.SERIE_A, 73, "Cagliari"),
    BOLOGNA: new Club(LEAGUES.SERIE_A, 76, "Bologna"),
    LAZIO: new Club(LEAGUES.SERIE_A, 78, "Lazio"),
    JUVENTUS: new Club(LEAGUES.SERIE_A, 80, "Juventus"),
    PARMA: new Club(LEAGUES.SERIE_A, 73, "Parma"),
    // HELLAS_VERONA: new Club(LEAGUES.SERIE_A, 73),
    ATALANTA: new Club(LEAGUES.SERIE_A, 79, "Atalanta"),
    // PISA: new Club(LEAGUES.SERIE_A, 72),
    GENOA: new Club(LEAGUES.SERIE_A, 73, "Genoa"),
    LECCE: new Club(LEAGUES.SERIE_A, 71, "Lecce"),
    SASSUOLO: new Club(LEAGUES.SERIE_A, 74, "Sassuolo"),
    // CREMONESE: new Club(LEAGUES.SERIE_A, 73),
    UDINESE: new Club(LEAGUES.SERIE_A, 73, "Udinese"),
    AS_ROMA: new Club(LEAGUES.SERIE_A, 80, "AS Roma"),
    COMO: new Club(LEAGUES.SERIE_A, 77, "Como"),
    INTER_MEDIOLAN: new Club(LEAGUES.SERIE_A, 83, "Inter Mediolan"),
    AC_MILAN: new Club(LEAGUES.SERIE_A, 81, "AC Milan")
};

export const LA_LIGA_CLUBS = {
    RCD_ESPANYOL: new Club(LEAGUES.LALIGA_EA_SPORTS, 75, "RCD Espanyol"),
    REAL_MADRID: new Club(LEAGUES.LALIGA_EA_SPORTS, 85, "Real Madrid"),
    RC_CELTA: new Club(LEAGUES.LALIGA_EA_SPORTS, 76, "RC Celta"),
    ATLETICO_DE_MADRID: new Club(LEAGUES.LALIGA_EA_SPORTS, 82, "Atlético de Madrid"),
    FC_BARCELONA: new Club(LEAGUES.LALIGA_EA_SPORTS, 85, "FC Barcelona"),
    CA_OSASUNA: new Club(LEAGUES.LALIGA_EA_SPORTS, 77, "CA Osasuna"),
    REAL_SOCIEDAD: new Club(LEAGUES.LALIGA_EA_SPORTS, 78, "Real Sociedad"),
    D_ALAVES: new Club(LEAGUES.LALIGA_EA_SPORTS, 74, "D. Alavés"),
    SEVILLA_FC: new Club(LEAGUES.LALIGA_EA_SPORTS, 75, "Sevilla FC"),
    // GIRONA_FC: new Club(LEAGUES.LALIGA_EA_SPORTS, 77),
    ATHLETIC_CLUB: new Club(LEAGUES.LALIGA_EA_SPORTS, 80, "Athletic Club"),
    // R_OVIEDO: new Club(LEAGUES.LALIGA_EA_SPORTS, 73),
    VILLARREAL_CF: new Club(LEAGUES.LALIGA_EA_SPORTS, 79, "Villarreal CF"),
    LEVANTE_UD: new Club(LEAGUES.LALIGA_EA_SPORTS, 74, "Levante UD"),
    REAL_BETIS: new Club(LEAGUES.LALIGA_EA_SPORTS, 79, "Real Betis"),
    // RCD_MALLORCA: new Club(LEAGUES.LALIGA_EA_SPORTS, 76),
    ELCHE_CF: new Club(LEAGUES.LALIGA_EA_SPORTS, 74, "Elche CF"),
    VALENCIA_CF: new Club(LEAGUES.LALIGA_EA_SPORTS, 76, "Valencia CF"),
    GETAFE_CF: new Club(LEAGUES.LALIGA_EA_SPORTS, 76, "Getafe CF"),
    RAYO_VALLECANO: new Club(LEAGUES.LALIGA_EA_SPORTS, 77, "Rayo Vallecano")
};

export const EKSTRAKLASA_CLUBS = {
    RAKOW: new Club(LEAGUES.EKSTRAKLASA, 69, "Raków"),
    PIAST_GLIWICE: new Club(LEAGUES.EKSTRAKLASA, 66, "Piast Gliwice"),
    GKS_KATOWICE: new Club(LEAGUES.EKSTRAKLASA, 67, "GKS Katowice"),
    LEGIA_WARSZAWA: new Club(LEAGUES.EKSTRAKLASA, 68, "Legia Warszawa"),
    ZAGLEBIE_LUBIN: new Club(LEAGUES.EKSTRAKLASA, 66, "Zagłębie Lubin"),
    LECH_POZNAN: new Club(LEAGUES.EKSTRAKLASA, 70, "Lech Poznań"),
    JAGIELLONIA: new Club(LEAGUES.EKSTRAKLASA, 69, "Jagiellonia"),
    GORNIK_ZABRZE: new Club(LEAGUES.EKSTRAKLASA, 68, "Górnik Zabrze"),
    WISLA_PLOCK: new Club(LEAGUES.EKSTRAKLASA, 65, "Wisła Płock"),
    WISLA_KRAKOW: new Club(LEAGUES.EKSTRAKLASA, 66, "Wisła Kraków"),
    WIDZEW_LODZ: new Club(LEAGUES.EKSTRAKLASA, 69, "Widzew Łódź"),
    CRACOVIA: new Club(LEAGUES.EKSTRAKLASA, 67, "Cracovia"),
    POGON_SZCZECIN: new Club(LEAGUES.EKSTRAKLASA, 68, "Pogoń Szczecin"),
    RADOMIAK_RADOM: new Club(LEAGUES.EKSTRAKLASA, 66, "Radomiak Radom"),
    WIECZYSTA: new Club(LEAGUES.EKSTRAKLASA, 64, "Wieczysta"),
    MOTOR_LUBLIN: new Club(LEAGUES.EKSTRAKLASA, 66, "Motor Lublin"),
    KORONA_KIELCE: new Club(LEAGUES.EKSTRAKLASA, 66, "Korona Kielce"),
    SLASK_WROCLAW: new Club(LEAGUES.EKSTRAKLASA, 64, "Śląsk Wrocław")
};